-- ITAJAÓ CAFÉS ESPECIAIS — ponte do checkout próprio para o CRM existente.
--
-- IMPORTANTE: o CRM já possui customers, orders, order_items, payments,
-- products e sales_channels. Esta migration NÃO cria uma segunda tabela de
-- pedidos. Ela cria apenas metadados técnicos das integrações e uma função
-- privada/atômica para registrar a compra nas tabelas reais do CRM.

create extension if not exists pgcrypto;

create table if not exists public.site_order_integrations (
  order_id uuid primary key references public.orders(id) on delete cascade,
  public_token uuid not null default gen_random_uuid() unique,
  checkout_status text not null default 'awaiting_payment'
    check (checkout_status in ('awaiting_payment','paid','payment_failed','cancelled','refunded','processing','fulfilled','checkout_error')),
  customer_snapshot jsonb not null default '{}'::jsonb,
  delivery_address jsonb not null default '{}'::jsonb,
  shipping_cost numeric(12,2) not null default 0 check (shipping_cost >= 0),
  shipping_service_id integer not null,
  shipping_service_name text not null,
  shipping_carrier text,
  shipping_quote jsonb,
  mp_preference_id text unique,
  mp_payment_id text unique,
  mp_payment_status text,
  bling_contact_id bigint,
  bling_order_id bigint,
  nfe_id bigint,
  nfe_key text,
  melhorenvio_order_id text,
  label_url text,
  integration_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.integration_tokens (
  provider text primary key check (provider in ('bling','melhorenvio')),
  access_token text not null,
  refresh_token text,
  token_type text,
  scope text,
  expires_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.store_integration_events (
  id bigint generated by default as identity primary key,
  order_id uuid references public.orders(id) on delete cascade,
  provider text not null,
  event_type text not null,
  external_id text,
  ok boolean not null default true,
  detail text,
  created_at timestamptz not null default now()
);

create index if not exists store_integration_events_order_idx
  on public.store_integration_events (order_id, created_at desc);

alter table public.site_order_integrations enable row level security;
alter table public.integration_tokens enable row level security;
alter table public.store_integration_events enable row level security;

revoke all on table public.site_order_integrations from anon, authenticated;
revoke all on table public.integration_tokens from anon, authenticated;
revoke all on table public.store_integration_events from anon, authenticated;

create or replace function public.touch_site_order_integration_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists site_order_integrations_touch_updated_at on public.site_order_integrations;
create trigger site_order_integrations_touch_updated_at
before update on public.site_order_integrations
for each row execute function public.touch_site_order_integration_updated_at();

-- Registra comprador + pedido + itens + metadados do checkout em uma única
-- transação. A função só pode ser chamada pelo backend com papel service_role.
create or replace function public.create_site_checkout_order(
  p_customer jsonb,
  p_address jsonb,
  p_items jsonb,
  p_subtotal numeric,
  p_shipping_amount numeric,
  p_shipping_cost numeric,
  p_shipping_service_id integer,
  p_shipping_service_name text,
  p_shipping_carrier text,
  p_shipping_quote jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_channel_id uuid;
  v_customer_id uuid;
  v_order_id uuid := gen_random_uuid();
  v_public_token uuid := gen_random_uuid();
  v_order_number text;
  v_document text := regexp_replace(coalesce(p_customer->>'document', ''), '[^0-9]', '', 'g');
  v_email text := lower(trim(coalesce(p_customer->>'email', '')));
  v_item jsonb;
  v_product_id uuid;
  v_product_cost numeric;
  v_sku text;
  v_quantity integer;
  v_unit_price numeric;
  v_total numeric;
begin
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'Pedido sem itens';
  end if;

  v_total := round((coalesce(p_subtotal, 0) + coalesce(p_shipping_amount, 0))::numeric, 2);
  if p_subtotal < 0 or p_shipping_amount < 0 or p_shipping_cost < 0 or v_total < 0 then
    raise exception 'Valores do pedido inválidos';
  end if;

  -- Evita criar dois canais "Site" em checkouts simultâneos.
  perform pg_advisory_xact_lock(hashtext('itajao:sales-channel:site')::bigint);
  select id
    into v_channel_id
    from public.sales_channels
   where lower(name) = 'site'
   order by active desc, created_at asc
   limit 1;

  if v_channel_id is null then
    insert into public.sales_channels (name, channel_type)
    values ('Site', 'loja_virtual')
    returning id into v_channel_id;
  end if;

  -- CPF/CNPJ é a primeira chave de deduplicação; e-mail é o fallback.
  perform pg_advisory_xact_lock(hashtext('itajao:customer:' || coalesce(nullif(v_document, ''), v_email))::bigint);
  if v_document <> '' then
    select id
      into v_customer_id
      from public.customers
     where regexp_replace(coalesce(cpf_cnpj, ''), '[^0-9]', '', 'g') = v_document
     order by active desc, created_at asc
     limit 1;
  end if;

  if v_customer_id is null and v_email <> '' then
    select id
      into v_customer_id
      from public.customers
     where lower(coalesce(email, '')) = v_email
     order by active desc, created_at asc
     limit 1;
  end if;

  if v_customer_id is null then
    insert into public.customers (
      customer_type, full_name, company_name, cpf_cnpj, phone, email,
      city, state, postal_code, address_line, address_number,
      address_complement, neighborhood, source_channel_id, active
    ) values (
      case when length(v_document) = 14 then 'empresa' else 'pessoa_fisica' end,
      p_customer->>'name',
      case when length(v_document) = 14 then p_customer->>'name' else null end,
      nullif(v_document, ''), p_customer->>'phone', nullif(v_email, ''),
      p_address->>'city', p_address->>'state', p_address->>'postalCode',
      p_address->>'street', p_address->>'number', nullif(p_address->>'complement', ''),
      p_address->>'district', v_channel_id, true
    ) returning id into v_customer_id;
  else
    update public.customers
       set full_name = p_customer->>'name',
           customer_type = case when length(v_document) = 14 then 'empresa' else 'pessoa_fisica' end,
           company_name = case when length(v_document) = 14 then coalesce(company_name, p_customer->>'name') else company_name end,
           cpf_cnpj = nullif(v_document, ''),
           phone = p_customer->>'phone',
           email = nullif(v_email, ''),
           city = p_address->>'city',
           state = p_address->>'state',
           postal_code = p_address->>'postalCode',
           address_line = p_address->>'street',
           address_number = p_address->>'number',
           address_complement = nullif(p_address->>'complement', ''),
           neighborhood = p_address->>'district',
           source_channel_id = coalesce(source_channel_id, v_channel_id),
           active = true,
           updated_at = now()
     where id = v_customer_id;
  end if;

  v_order_number := 'SITE-' || to_char(clock_timestamp() at time zone 'America/Sao_Paulo', 'YYYYMMDD-HH24MISS') || '-' || upper(left(replace(v_order_id::text, '-', ''), 6));

  insert into public.orders (
    id, customer_id, channel_id, external_order_number, order_date,
    payment_status, subtotal, discount_amount, shipping_amount, total_amount,
    notes
  ) values (
    v_order_id, v_customer_id, v_channel_id, v_order_number, now(),
    'pendente', p_subtotal, 0, p_shipping_amount, v_total,
    'Pedido criado automaticamente pelo checkout do site Itajaó.'
  );

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    v_sku := trim(coalesce(v_item->>'sku', ''));
    v_quantity := (v_item->>'quantity')::integer;
    v_unit_price := (v_item->>'unitPrice')::numeric;

    if v_sku = '' or v_quantity < 1 or v_unit_price < 0 then
      raise exception 'Item do pedido inválido';
    end if;

    perform pg_advisory_xact_lock(hashtext('itajao:product:' || v_sku)::bigint);
    select id, cost_price
      into v_product_id, v_product_cost
      from public.products
     where sku = v_sku
     order by active desc, created_at asc
     limit 1;

    if v_product_id is null then
      insert into public.products (sku, name, weight_grams, sale_price, active)
      values (
        v_sku,
        v_item->>'name',
        nullif(v_item->>'weightGrams', '')::integer,
        v_unit_price,
        true
      )
      returning id, cost_price into v_product_id, v_product_cost;
    end if;

    insert into public.order_items (
      order_id, product_id, product_name, quantity,
      unit_price, unit_cost, line_total
    ) values (
      v_order_id, v_product_id, v_item->>'name', v_quantity,
      v_unit_price, v_product_cost, round((v_unit_price * v_quantity)::numeric, 2)
    );
  end loop;

  insert into public.site_order_integrations (
    order_id, public_token, checkout_status, customer_snapshot,
    delivery_address, shipping_cost, shipping_service_id,
    shipping_service_name, shipping_carrier, shipping_quote
  ) values (
    v_order_id, v_public_token, 'awaiting_payment', p_customer,
    p_address, p_shipping_cost, p_shipping_service_id,
    p_shipping_service_name, p_shipping_carrier, p_shipping_quote
  );

  return jsonb_build_object(
    'id', v_order_id,
    'public_token', v_public_token,
    'order_number', v_order_number,
    'customer_id', v_customer_id,
    'channel_id', v_channel_id,
    'total', v_total
  );
end;
$$;

revoke all on function public.create_site_checkout_order(jsonb,jsonb,jsonb,numeric,numeric,numeric,integer,text,text,jsonb) from public;
revoke all on function public.create_site_checkout_order(jsonb,jsonb,jsonb,numeric,numeric,numeric,integer,text,text,jsonb) from anon, authenticated;
grant execute on function public.create_site_checkout_order(jsonb,jsonb,jsonb,numeric,numeric,numeric,integer,text,text,jsonb) to service_role;

-- Se uma versão antiga desta migration chegou a criar public.store_orders,
-- ela é deliberadamente preservada. O novo código não lê nem grava nela;
-- assim nenhum dado existente é apagado automaticamente.
