-- ITAJAÓ CAFÉS ESPECIAIS — checkout próprio e integrações.
-- As tabelas abaixo são acessadas apenas pelas Edge Functions com service role.

create extension if not exists pgcrypto;

create table if not exists public.store_orders (
  id uuid primary key default gen_random_uuid(),
  order_number bigint generated by default as identity unique,
  public_token uuid not null default gen_random_uuid(),
  status text not null default 'awaiting_payment'
    check (status in ('awaiting_payment','paid','payment_failed','cancelled','refunded','processing','fulfilled','checkout_error')),
  customer jsonb not null,
  delivery_address jsonb not null,
  items jsonb not null,
  subtotal numeric(12,2) not null check (subtotal >= 0),
  shipping_amount numeric(12,2) not null check (shipping_amount >= 0),
  shipping_cost numeric(12,2) not null check (shipping_cost >= 0),
  total numeric(12,2) not null check (total >= 0),
  shipping_service_id integer not null,
  shipping_service_name text not null,
  shipping_carrier text,
  shipping_quote jsonb,
  mp_preference_id text unique,
  mp_payment_id text unique,
  mp_payment_status text,
  bling_contact_id bigint,
  bling_order_id bigint,
  nfe_id bigint,
  nfe_key text,
  melhorenvio_order_id text,
  tracking_code text,
  label_url text,
  integration_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists store_orders_public_access_idx
  on public.store_orders (id, public_token);

create table if not exists public.integration_tokens (
  provider text primary key check (provider in ('bling','melhorenvio')),
  access_token text not null,
  refresh_token text,
  token_type text,
  scope text,
  expires_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.store_integration_events (
  id bigint generated by default as identity primary key,
  order_id uuid references public.store_orders(id) on delete cascade,
  provider text not null,
  event_type text not null,
  external_id text,
  ok boolean not null default true,
  detail text,
  created_at timestamptz not null default now()
);

create index if not exists store_integration_events_order_idx
  on public.store_integration_events (order_id, created_at desc);

alter table public.store_orders enable row level security;
alter table public.integration_tokens enable row level security;
alter table public.store_integration_events enable row level security;

revoke all on table public.store_orders from anon, authenticated;
revoke all on table public.integration_tokens from anon, authenticated;
revoke all on table public.store_integration_events from anon, authenticated;

create or replace function public.touch_store_order_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists store_orders_touch_updated_at on public.store_orders;
create trigger store_orders_touch_updated_at
before update on public.store_orders
for each row execute function public.touch_store_order_updated_at();

