-- ITAJAÓ CAFÉS ESPECIAIS — central de e-mails e Comunidade Itajaó.
--
-- Todas as tabelas abaixo são privadas para o navegador. O site público usa
-- Edge Functions que validam os dados e devolvem somente campos publicados.

begin;

-- ---------------------------------------------------------------------------
-- Central única de e-mails
-- ---------------------------------------------------------------------------

create table if not exists public.email_outbox (
  id uuid primary key default gen_random_uuid(),
  category text not null
    check (category in ('transactional', 'marketing', 'internal', 'auth')),
  template_key text not null
    check (template_key ~ '^[a-z0-9_]{3,80}$'),
  recipient_email text not null
    check (recipient_email = lower(recipient_email) and char_length(recipient_email) between 5 and 180),
  recipient_name text,
  sender_kind text not null default 'customer'
    check (sender_kind in ('customer', 'admin')),
  subject text not null check (char_length(subject) between 1 and 180),
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'sent', 'failed', 'dead', 'suppressed', 'cancelled')),
  priority smallint not null default 100 check (priority between 0 and 1000),
  attempts smallint not null default 0 check (attempts >= 0),
  max_attempts smallint not null default 5 check (max_attempts between 1 and 20),
  next_attempt_at timestamptz,
  claimed_at timestamptz,
  claim_token uuid,
  provider text not null default 'resend',
  provider_message_id text,
  provider_error text,
  idempotency_key text not null unique,
  related_order_id uuid references public.orders(id) on delete set null,
  related_customer_id uuid references public.customers(id) on delete set null,
  resource_type text,
  resource_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  sent_at timestamptz,
  cancelled_at timestamptz
);

create index if not exists email_outbox_dispatch_idx
  on public.email_outbox (priority, next_attempt_at, created_at)
  where status in ('pending', 'failed');

create index if not exists email_outbox_provider_message_idx
  on public.email_outbox (provider_message_id)
  where provider_message_id is not null;

create index if not exists email_outbox_order_idx
  on public.email_outbox (related_order_id, created_at desc)
  where related_order_id is not null;

create table if not exists public.email_events (
  id bigint generated by default as identity primary key,
  outbox_id uuid references public.email_outbox(id) on delete set null,
  provider text not null default 'resend',
  provider_event_id text not null unique,
  provider_message_id text,
  event_type text not null,
  occurred_at timestamptz not null,
  event_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists email_events_message_idx
  on public.email_events (provider_message_id, occurred_at desc);

create table if not exists public.email_suppressions (
  email text primary key
    check (email = lower(email) and char_length(email) between 5 and 180),
  reason text not null
    check (reason in ('unsubscribed', 'bounced', 'complained', 'manual')),
  source text not null default 'system',
  detail text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.newsletter_subscribers
  add column if not exists unsubscribe_token uuid not null default gen_random_uuid();

create unique index if not exists newsletter_subscribers_unsubscribe_token_key
  on public.newsletter_subscribers (unsubscribe_token);

-- ---------------------------------------------------------------------------
-- Comunidade Itajaó
-- ---------------------------------------------------------------------------

create table if not exists public.review_invites (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  customer_id uuid not null references public.customers(id) on delete cascade,
  link_token_hash text not null unique
    check (link_token_hash ~ '^[0-9a-f]{64}$'),
  code_hash text not null
    check (code_hash ~ '^[0-9a-f]{64}$'),
  status text not null default 'pending'
    check (status in ('pending', 'used', 'expired', 'revoked', 'locked')),
  attempts smallint not null default 0 check (attempts between 0 and 5),
  max_attempts smallint not null default 5 check (max_attempts = 5),
  expires_at timestamptz not null,
  last_attempt_at timestamptz,
  verified_at timestamptz,
  used_at timestamptz,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (expires_at > created_at)
);

create unique index if not exists review_invites_one_open_per_order
  on public.review_invites (order_id)
  where status = 'pending';

create index if not exists review_invites_expiration_idx
  on public.review_invites (status, expires_at);

create table if not exists public.product_reviews (
  id uuid primary key default gen_random_uuid(),
  invite_id uuid not null references public.review_invites(id) on delete restrict,
  order_id uuid not null references public.orders(id) on delete restrict,
  order_item_id uuid not null references public.order_items(id) on delete restrict,
  product_id uuid not null references public.products(id) on delete restrict,
  customer_id uuid not null references public.customers(id) on delete restrict,
  reviewer_first_name text not null check (char_length(reviewer_first_name) between 1 and 80),
  reviewer_last_name text check (reviewer_last_name is null or char_length(reviewer_last_name) <= 100),
  rating smallint not null check (rating between 1 and 5),
  title text check (title is null or char_length(title) <= 120),
  comment text not null check (char_length(comment) between 3 and 2000),
  media_path text,
  verified_purchase boolean not null default true,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected')),
  admin_response text check (admin_response is null or char_length(admin_response) <= 1500),
  admin_responded_at timestamptz,
  moderation_notes text,
  moderated_by uuid references auth.users(id) on delete set null,
  moderated_at timestamptz,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (order_item_id)
);

create index if not exists product_reviews_public_feed_idx
  on public.product_reviews (product_id, published_at desc)
  where status = 'approved';

create index if not exists product_reviews_moderation_idx
  on public.product_reviews (status, created_at);

create table if not exists public.recipe_submissions (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid references public.customers(id) on delete set null,
  author_name text not null check (char_length(author_name) between 2 and 120),
  email text not null
    check (email = lower(email) and char_length(email) between 5 and 180),
  title text not null check (char_length(title) between 3 and 140),
  introduction text check (introduction is null or char_length(introduction) <= 500),
  ingredients text not null check (char_length(ingredients) between 5 and 4000),
  instructions text not null check (char_length(instructions) between 10 and 8000),
  prep_minutes integer check (prep_minutes is null or prep_minutes between 1 and 1440),
  servings text check (servings is null or char_length(servings) <= 80),
  image_path text,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected')),
  admin_response text check (admin_response is null or char_length(admin_response) <= 1500),
  moderation_notes text,
  moderated_by uuid references auth.users(id) on delete set null,
  moderated_at timestamptz,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists recipe_submissions_public_feed_idx
  on public.recipe_submissions (published_at desc)
  where status = 'approved';

create index if not exists recipe_submissions_moderation_idx
  on public.recipe_submissions (status, created_at);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'community-media',
  'community-media',
  false,
  6291456,
  array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

-- Novos avisos aparecem também no sino do CRM.
alter table public.crm_notifications
  drop constraint if exists crm_notifications_kind_check;

alter table public.crm_notifications
  add constraint crm_notifications_kind_check check (
    kind in (
      'sale_created', 'stock_low', 'stock_critical', 'stock_out',
      'payment_pending', 'ranking_changed', 'reseller_inactive',
      'weekly_summary', 'monthly_summary', 'review_received',
      'recipe_received', 'review_invite_due'
    )
  );

-- Depois de 3 dias, o pedido entra no sino do CRM para que a equipe abra o
-- WhatsApp já com link e código gerados pelo endpoint community-admin.
create or replace function public.crm_generate_review_invite_reminders()
returns integer
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_inserted integer;
begin
  insert into public.crm_notifications (
    recipient_user_id, recipient_reseller_id, kind, severity,
    title, message, event_key, metadata
  )
  select
    profile.user_id,
    null,
    'review_invite_due',
    'info',
    'Pedido pronto para pedir avaliação',
    'O pedido ' || coalesce(order_row.external_order_number, left(order_row.id::text, 8)) ||
      ' já pode receber o convite de avaliação pelo WhatsApp.',
    'review-invite-due:' || order_row.id::text,
    jsonb_build_object(
      'order_id', order_row.id,
      'customer_id', order_row.customer_id,
      'action', 'create_review_invite'
    )
  from public.orders as order_row
  cross join public.profiles as profile
  where profile.role = 'admin'
    and profile.active = true
    and order_row.payment_status = 'pago'
    and order_row.order_date <= now() - interval '3 days'
    and order_row.status not in ('cancelado', 'reembolsado')
    and exists (
      select 1
      from public.order_items as item
      where item.order_id = order_row.id
        and item.product_id is not null
        and not exists (
          select 1 from public.product_reviews as review
          where review.order_item_id = item.id
        )
    )
    and not exists (
      select 1
      from public.review_invites as invite
      where invite.order_id = order_row.id
        and invite.status in ('pending', 'used')
    )
  on conflict (recipient_user_id, event_key) do nothing;

  get diagnostics v_inserted = row_count;
  return v_inserted;
end;
$$;

revoke all on function public.crm_generate_review_invite_reminders() from public, anon, authenticated;
grant execute on function public.crm_generate_review_invite_reminders() to service_role;

-- ---------------------------------------------------------------------------
-- Segurança e permissões
-- ---------------------------------------------------------------------------

alter table public.email_outbox enable row level security;
alter table public.email_events enable row level security;
alter table public.email_suppressions enable row level security;
alter table public.review_invites enable row level security;
alter table public.product_reviews enable row level security;
alter table public.recipe_submissions enable row level security;

revoke all on table public.email_outbox from public, anon, authenticated;
revoke all on table public.email_events from public, anon, authenticated;
revoke all on table public.email_suppressions from public, anon, authenticated;
revoke all on table public.review_invites from public, anon, authenticated;
revoke all on table public.product_reviews from public, anon, authenticated;
revoke all on table public.recipe_submissions from public, anon, authenticated;

grant select, insert, update, delete on table public.email_outbox to service_role;
grant select, insert, update, delete on table public.email_events to service_role;
grant select, insert, update, delete on table public.email_suppressions to service_role;
grant select, insert, update, delete on table public.review_invites to service_role;
grant select, insert, update, delete on table public.product_reviews to service_role;
grant select, insert, update, delete on table public.recipe_submissions to service_role;
grant usage, select on sequence public.email_events_id_seq to service_role;

create or replace function public.touch_community_updated_at()
returns trigger
language plpgsql
set search_path = pg_catalog, public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists email_outbox_touch_updated_at on public.email_outbox;
create trigger email_outbox_touch_updated_at
before update on public.email_outbox
for each row execute function public.touch_community_updated_at();

drop trigger if exists email_suppressions_touch_updated_at on public.email_suppressions;
create trigger email_suppressions_touch_updated_at
before update on public.email_suppressions
for each row execute function public.touch_community_updated_at();

drop trigger if exists review_invites_touch_updated_at on public.review_invites;
create trigger review_invites_touch_updated_at
before update on public.review_invites
for each row execute function public.touch_community_updated_at();

drop trigger if exists product_reviews_touch_updated_at on public.product_reviews;
create trigger product_reviews_touch_updated_at
before update on public.product_reviews
for each row execute function public.touch_community_updated_at();

drop trigger if exists recipe_submissions_touch_updated_at on public.recipe_submissions;
create trigger recipe_submissions_touch_updated_at
before update on public.recipe_submissions
for each row execute function public.touch_community_updated_at();

revoke all on function public.touch_community_updated_at() from public, anon, authenticated;

-- Insere um e-mail uma única vez. A função fica inacessível ao navegador e é
-- usada apenas pelas Edge Functions e pelos gatilhos internos.
create or replace function public.enqueue_email(
  p_category text,
  p_template_key text,
  p_recipient_email text,
  p_recipient_name text,
  p_sender_kind text,
  p_subject text,
  p_payload jsonb,
  p_idempotency_key text,
  p_related_order_id uuid default null,
  p_related_customer_id uuid default null,
  p_resource_type text default null,
  p_resource_id uuid default null,
  p_priority smallint default 100
)
returns uuid
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_email text := lower(trim(coalesce(p_recipient_email, '')));
  v_status text := 'pending';
  v_id uuid;
  v_reason text;
begin
  if v_email = '' or v_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then
    raise exception 'E-mail inválido';
  end if;

  select reason into v_reason
    from public.email_suppressions
   where email = v_email;

  if v_reason in ('bounced', 'complained', 'manual')
     or (v_reason = 'unsubscribed' and p_category = 'marketing') then
    v_status := 'suppressed';
  end if;

  insert into public.email_outbox (
    category, template_key, recipient_email, recipient_name, sender_kind,
    subject, payload, status, priority, next_attempt_at, idempotency_key,
    related_order_id, related_customer_id, resource_type, resource_id
  ) values (
    p_category, p_template_key, v_email, nullif(trim(p_recipient_name), ''),
    p_sender_kind, p_subject, coalesce(p_payload, '{}'::jsonb), v_status,
    p_priority, case when v_status = 'pending' then now() else null end,
    p_idempotency_key, p_related_order_id, p_related_customer_id,
    p_resource_type, p_resource_id
  )
  on conflict (idempotency_key) do nothing
  returning id into v_id;

  if v_id is null then
    select id into v_id
      from public.email_outbox
     where idempotency_key = p_idempotency_key;
  end if;

  return v_id;
end;
$$;

-- Reserva lotes com SKIP LOCKED para evitar disparos duplicados quando duas
-- execuções do agendador se sobrepõem.
create or replace function public.claim_email_outbox(p_limit integer default 25)
returns setof public.email_outbox
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
  update public.email_outbox
     set status = 'pending',
         claim_token = null,
         claimed_at = null,
         next_attempt_at = now(),
         provider_error = coalesce(provider_error, 'Processamento anterior expirou.')
   where status = 'processing'
     and claimed_at < now() - interval '15 minutes';

  return query
  with picked as (
    select id
      from public.email_outbox
     where status in ('pending', 'failed')
       and attempts < max_attempts
       and coalesce(next_attempt_at, now()) <= now()
     order by priority asc, created_at asc
     for update skip locked
     limit greatest(1, least(coalesce(p_limit, 25), 100))
  )
  update public.email_outbox as outbox
     set status = 'processing',
         attempts = outbox.attempts + 1,
         claimed_at = now(),
         claim_token = gen_random_uuid(),
         updated_at = now()
    from picked
   where outbox.id = picked.id
  returning outbox.*;
end;
$$;

create or replace function public.complete_email_outbox(
  p_id uuid,
  p_claim_token uuid,
  p_success boolean,
  p_provider_message_id text default null,
  p_error text default null
)
returns boolean
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_updated integer;
begin
  update public.email_outbox
     set status = case
           when p_success then 'sent'
           when attempts >= max_attempts then 'dead'
           else 'failed'
         end,
         provider_message_id = case when p_success then p_provider_message_id else provider_message_id end,
         provider_error = case when p_success then null else left(coalesce(p_error, 'Falha desconhecida.'), 1500) end,
         sent_at = case when p_success then now() else sent_at end,
         next_attempt_at = case
           when p_success or attempts >= max_attempts then null
           else now() + make_interval(mins => (power(2, least(attempts, 6)))::integer)
         end,
         claimed_at = null,
         claim_token = null,
         updated_at = now()
   where id = p_id
     and status = 'processing'
     and claim_token = p_claim_token;

  get diagnostics v_updated = row_count;
  return v_updated = 1;
end;
$$;

revoke all on function public.enqueue_email(text, text, text, text, text, text, jsonb, text, uuid, uuid, text, uuid, smallint) from public, anon, authenticated;
revoke all on function public.claim_email_outbox(integer) from public, anon, authenticated;
revoke all on function public.complete_email_outbox(uuid, uuid, boolean, text, text) from public, anon, authenticated;

grant execute on function public.enqueue_email(text, text, text, text, text, text, jsonb, text, uuid, uuid, text, uuid, smallint) to service_role;
grant execute on function public.claim_email_outbox(integer) to service_role;
grant execute on function public.complete_email_outbox(uuid, uuid, boolean, text, text) to service_role;

-- E-mails de mudanças do pedido são gerados no banco para cobrir tanto o
-- checkout quanto atualizações feitas depois no CRM/Bling.
create or replace function public.queue_store_order_email()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_customer_name text;
  v_customer_email text;
  v_public_token uuid;
  v_template text;
  v_subject text;
  v_key text;
begin
  select public_token
    into v_public_token
    from public.site_order_integrations
   where order_id = new.id;

  if v_public_token is null then
    return new;
  end if;

  select full_name, lower(email)
    into v_customer_name, v_customer_email
    from public.customers
   where id = new.customer_id;

  if coalesce(v_customer_email, '') = '' then
    return new;
  end if;

  if old.payment_status is distinct from new.payment_status then
    if new.payment_status = 'pago' then
      v_template := 'payment_approved';
      v_subject := 'Pagamento aprovado — pedido ' || coalesce(new.external_order_number, left(new.id::text, 8));
    elsif new.payment_status = 'cancelado' then
      v_template := 'payment_cancelled';
      v_subject := 'Pagamento cancelado — pedido ' || coalesce(new.external_order_number, left(new.id::text, 8));
    elsif new.payment_status = 'reembolsado' then
      v_template := 'payment_refunded';
      v_subject := 'Pagamento reembolsado — pedido ' || coalesce(new.external_order_number, left(new.id::text, 8));
    end if;

    if v_template is not null then
      v_key := 'order:' || new.id::text || ':payment:' || new.payment_status;
      perform public.enqueue_email(
        'transactional', v_template, v_customer_email, v_customer_name,
        'customer', v_subject,
        jsonb_build_object(
          'customer_name', v_customer_name,
          'order_id', new.id,
          'order_number', new.external_order_number,
          'total_amount', new.total_amount,
          'public_token', v_public_token,
          'payment_status', new.payment_status
        ),
        v_key, new.id, new.customer_id, 'order', new.id, 20
      );
    end if;
  end if;

  if new.status = 'enviado'
     and (old.status is distinct from new.status or old.tracking_code is distinct from new.tracking_code) then
    perform public.enqueue_email(
      'transactional', 'order_shipped', v_customer_email, v_customer_name,
      'customer', 'Seu Café Itajaó foi enviado',
      jsonb_build_object(
        'customer_name', v_customer_name,
        'order_id', new.id,
        'order_number', new.external_order_number,
        'public_token', v_public_token,
        'tracking_code', new.tracking_code,
        'expected_delivery_date', new.expected_delivery_date
      ),
      'order:' || new.id::text || ':shipped:' || coalesce(new.tracking_code, 'sem-rastreio'),
      new.id, new.customer_id, 'order', new.id, 30
    );
  end if;

  if new.status = 'entregue' and old.status is distinct from new.status then
    perform public.enqueue_email(
      'transactional', 'order_delivered', v_customer_email, v_customer_name,
      'customer', 'Pedido entregue — aproveite seu Café Itajaó',
      jsonb_build_object(
        'customer_name', v_customer_name,
        'order_id', new.id,
        'order_number', new.external_order_number,
        'public_token', v_public_token,
        'delivered_at', coalesce(new.delivered_at, now())
      ),
      'order:' || new.id::text || ':delivered',
      new.id, new.customer_id, 'order', new.id, 30
    );
  end if;

  return new;
end;
$$;

drop trigger if exists orders_queue_store_email on public.orders;
create trigger orders_queue_store_email
after update of payment_status, status, tracking_code, expected_delivery_date on public.orders
for each row execute function public.queue_store_order_email();

revoke all on function public.queue_store_order_email() from public, anon, authenticated;

commit;
